### ISSUE TITLE
No Hindi translated texts or Hindi Language Added

### ISSUE THREAD

**Issue by chandankumarpanigrahi** [github-profile-achievements/hindi#1]
The Contents are in English Language. As per github-profile-achievements/hindi The content language should be in Hindi Language. But about 99% of the Content are in English Language.

**Comment by gomzyakov** [comment]
@chandankumarpanigrahi Hello!

Yes, there is no translation yet. The repository was created after comment https://github.com/orgs/github-profile-achievements/discussions/2#discussioncomment-6961301

@amanbabuhemant will make a PR with edits in the future or you can offer a Hindi translation in your PR

**Comment by amanbabuhemant** [comment]
@chandankumarpanigrahi, I am translating, issue will be close within a day, actually II was busy in some other work, sorry for late.

**Comment by amanbabuhemant** [comment]
@chandankumarpanigrahi, I have done translation you can review the pull request.
@gomzyakov, now you can close this issue, and review/merge pull request.

**Comment by gomzyakov** [comment]
@amanbabuhemant 

Thanks a lot! I merged your [PR](https://github.com/github-profile-achievements/hindi/pull/2)

@chandankumarpanigrahi 

Is the issue no longer relevant?

**Comment by chandankumarpanigrahi** [comment]
Issue has been solved. Thank You @amanbabuhemant and @gomzyakov

**Comment by amanbabuhemant** [comment]
It's my pleasure to contribute to your repo @gomzyakov .
May we do some more stuffs in future.
@chandankumarpanigrahi thanks for reminding, and sorry for late translation.
